# -*- coding: utf-8 -*-
"""
Created on Wed Dec  5 09:56:28 2018

test on quaternion

@author: JingQIN
"""

import matplotlib.pyplot as plt
from Quaternion import Quaternion
import functions as f
import numpy as np
from tempfile import TemporaryFile

print("-------test on addition operation-------")
A = Quaternion(-1.0, 2.0, 3.0, 4.0)
B = Quaternion(5.0, 6.0, 7.0, 8.0)
C = A + B
print(A)
print(B)
print(C)
print("-------test on subtraction operation-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
F = Quaternion(-2.0, 6.0, 7.0, 8.0)
G = E - F
print(E)
print(F)
print(G)
print("-------test on dot production-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
F = Quaternion(-2.0, 6.0, 7.0, 8.0)
G = E.dot(F)
print(E)
print(F)
print(G)
print("-------test on multiply-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
F = Quaternion(-2.0, 6.0, 7.0, 8.0)
G = E*F
print(E)
print(F)
print(G)
print("-------test on scalar multiply-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
F = 100
G = E.scalar_mul(F)
print(E)
print(F)
print(G)
print("-------test on norm-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
print(E.norm())
print("-------test on conjugate-------")
E = Quaternion(1.0, 2.0, 3.0, 4.0)
print(E.conj())
print("-------test on Quaternion to DCM-------")
E = Quaternion(0.0, 1.0, 1.0, 1.0)
D = E.toDCM()
print(D)
print("-------test on DCM to Quaternion-------")
print(f.DCMtoQuaternion(D))
#print("-------test on rotation precision------")
#(X1, X2, MEANDIFF, MINDIFF, MAXDIFF) = f.Quaternion_rotation_precision(30, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.semilogy(X1, MEANDIFF, 'k--', label='Mean', color = 'red')
#ax.semilogy(X1, MINDIFF, 'k:', label='MIN', color = 'green')
#ax.semilogy(X1, MAXDIFF, 'k', label='MAX', color = 'blue')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences in 100 steps, 30 rounds")
#legend = ax.legend(loc=2, bbox_to_anchor=(1.05,1.0),borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_Quaternion_100_test.png', dpi = 100)
#print("-------test on DCM rotation-------")
#(X1, X2, MEANDIFF, MINDIFF, MAXDIFF) = f.DCM_rotation_precision(30, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.semilogy(X1, MEANDIFF, 'k--', label='Mean', color = 'red')
#ax.semilogy(X1, MINDIFF, 'k:', label='MIN', color = 'green')
#ax.semilogy(X1, MAXDIFF, 'k', label='MAX', color = 'blue')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences in 100 steps, 30 rounds")
#legend = ax.legend(loc = 2, bbox_to_anchor = (1.05, 1.0), borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_DCM_100_test.png', dpi = 100)
#print("-------compare output differences in Quaternion and DCM-------")
#(X1, X2, MEANDIFF_Q, MINDIFF_Q, MAXDIFF_Q, MEANDIFF_DCM, MINDIFF_Q, MAXDIFF_Q) = f.Quaternion_DCM_precision(30, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.semilogy(X1, MEANDIFF_Q, 'k--', label='Mean_Quaternion', color = 'red')
#ax.semilogy(X1, MEANDIFF_DCM, 'k--', label='Mean_DCM', color = 'green')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences between DCM and Quaternion in 100 steps, 30 rounds")
#legend = ax.legend(loc = 2, bbox_to_anchor = (1.05, 1.0), borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_DCM_Quaternion_100_test.png', dpi = 100)
#print("-------Quaternion, DCM in 300 rounds, 100 steps-------")
#(X1, X2, MEANDIFF, MINDIFF, MAXDIFF) = f.Quaternion_rotation_precision(300, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.loglog(X1, MEANDIFF, 'k--', label='Mean', color = 'red')
#ax.loglog(X1, MINDIFF, 'k:', label='MIN', color = 'green')
#ax.loglog(X1, MAXDIFF, 'k', label='MAX', color = 'blue')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences in 100 steps, 300 rounds, loglog_plot")
#legend = ax.legend(loc=2, bbox_to_anchor=(1.05,1.0),borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_Quaternion_100_300_loglog.png', dpi = 100)
#
#(X1, X2, MEANDIFF, MINDIFF, MAXDIFF) = f.DCM_rotation_precision(300, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.loglog(X1, MEANDIFF, 'k--', label='Mean', color = 'red')
#ax.loglog(X1, MINDIFF, 'k:', label='MIN', color = 'green')
#ax.loglog(X1, MAXDIFF, 'k', label='MAX', color = 'blue')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences in 100 steps, 300 rounds, loglog_plot")
#legend = ax.legend(loc=2, bbox_to_anchor=(1.05,1.0),borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_DCM_100_300_loglog.png', dpi = 100)
#
#(X1, X2, MEANDIFF_Q, MINDIFF_Q, MAXDIFF_Q, MEANDIFF_DCM, MINDIFF_Q, MAXDIFF_Q) = f.Quaternion_DCM_precision(300, 100, np.pi, np.pi, np.pi)
#fig, ax = plt.subplots()
#ax.loglog(X1, MEANDIFF_Q, 'k--', label='Mean_Quaternion', color = 'red')
#ax.loglog(X1, MEANDIFF_DCM, 'k--', label='Mean_DCM', color = 'green')
#ax.set_xlabel("Times")
#ax.set_ylabel("Differences")
#ax.set_title("Differences between DCM and Quaternion in 100 steps, 300 rounds, loglog_plot")
#legend = ax.legend(loc = 2, bbox_to_anchor = (1.05, 1.0), borderaxespad = 0.)
#legend.get_frame().set_facecolor('C0')
#plt.show()
#fig.set_size_inches(18.5, 10.5)
#fig.savefig('test_DCM_Quaternion_100_300_loglog.png', dpi = 100)
print("--------test on rotator differences-------")
(X1, X2, DIAGONAL_CHECK_Q, OFF_DIAGONAL_CHECK_Q, ORTHONORMALITY_COL_Q, ORTHONORMALITY_ROW_Q, DIAGONAL_CHECK_DCM, OFF_DIAGONAL_CHECK_DCM, ORTHONORMALITY_COL_DCM, ORTHONORMALITY_ROW_DCM) = f.DCM_Quaternion_rotator_check(30, 1000, np.pi, np.pi, np.pi)
#x1 = TemporaryFile()
#np.save(x1, X1)
#x1.seek(0)
#np.load(x1)

fig, ax = plt.subplots()
ax.plot(X2, DIAGONAL_CHECK_Q, 'k--', label='Diagonal_check_Quaternion', color = 'red')
ax.plot(X2, DIAGONAL_CHECK_DCM, 'k--', label='Diagonal_check_DCM', color = 'green')
ax.set_xlabel("Times")
ax.set_ylabel("Diagonal_Differences")
ax.set_title("DCM and Quaternion in diagonal check")
legend = ax.legend(loc = 1)
legend.get_frame().set_facecolor('C0')
plt.show()
fig.savefig('test_DCM_Quaternion_diagonal_check.png', dpi = 100)

print(DIAGONAL_CHECK_Q)

fig, ax = plt.subplots()
ax.plot(X2, OFF_DIAGONAL_CHECK_Q, 'k--', label='Off_Diagonal_check_Quaternion', color = 'red')
ax.plot(X2, OFF_DIAGONAL_CHECK_DCM, 'k--', label='Off_Diagonal_check_DCM', color = 'green')
ax.set_xlabel("Times")
ax.set_ylabel("Off_Diagonal_Differences")
ax.set_title("DCM and Quaternion in off diagonal check")
legend = ax.legend(loc = 2)
legend.get_frame().set_facecolor('C0')
plt.show()
fig.savefig('test_DCM_Quaternion_off_diagonal_check.png', dpi = 100)

fig, ax = plt.subplots()
ax.plot(X2, ORTHONORMALITY_COL_Q, 'k--', label='ortho_col_check_Quaternion', color = 'red')
ax.plot(X2, ORTHONORMALITY_COL_DCM, 'k--', label='ortho_col_check_DCM', color = 'green')
ax.plot(X2, ORTHONORMALITY_ROW_Q, 'k--', label='ortho_col_check_Quaternion', color = 'blue')
ax.plot(X2, ORTHONORMALITY_ROW_DCM, 'k--', label='ortho_col_check_DCM', color = 'purple')
ax.set_xlabel("Times")
ax.set_ylabel("Orthonormality_check_col_row")
ax.set_title("Orthonormality_check")
legend = ax.legend(loc = 1)
legend.get_frame().set_facecolor('C0')
plt.show()
fig.savefig('test_DCM_Quaternion_orthonormality_check.png', dpi = 100)